### PR TITLE
Case sensitivity fix

### PR DESCRIPTION
**Pull request by QuantumEF**
Adds _most_ keywords into the match statement for allowing case insensitivity.
This is related to #49 

I was hoping that the regex expressions would allow for regex groups for some sort of wildcard match, but oh well.

It does not handle the "!OSRE" keyword case.

### CODE REVIEW

**Comment by jannic** [comment]
> It does not handle the "!OSRE" keyword case.

What's wrong with adding a rule to fix this?
```
  r"(?i)osre" => "osre",
```

Does that break something?

**Comment by QuantumEF** [comment]
It did not seem to recognize it. I will have another go at it tomorrow if I have time. Maybe I just misconfigured something.

**Comment by jannic** [comment]
`!` and `osre` are separate tokens. Perhaps you tried to handle `!osre` as a single token?

**Comment by QuantumEF** [comment]
Ok, so it turns out when I was initial trying to implement it, I just wrote a bad `jmp` instruction, and it was that simple.

**Review by jannic — APPROVED** [review]

**Pull request merged**
